export const SERVICES = {
  stores: { slug: 'stores', name: 'المتاجر', icon: '🛒' },
  restaurants: { slug: 'restaurants', name: 'المطاعم', icon: '🍽️' },
  hotels: { slug: 'hotels', name: 'الفنادق', icon: '🏨' },
  flights: { slug: 'flights', name: 'حجز الطيران', icon: '✈️' },
  travel_offices: { slug: 'travel_offices', name: 'مكاتب السفر', icon: '🧳' },
};

export const ROOM_TYPES = {
  standard: 'قياسية',
  family: 'عائلية',
  deluxe: 'ديلوكس',
  suite: 'جناح',
  presidential: 'رئاسي',
};

export const CATALOGS = {
  stores: {
    api: '/provider/products',
    itemType: 'products',
    categoriesApi: '/provider/product-categories',
    title: 'المنتجات',
    item: 'منتج',
    itemF: 'المنتج',
    icon: '🛍️',
    subtitle: 'أدر منتجات متجرك وأقسامها وأسعارها وخصوماتها وعروضها',
    columns: [
      { key: 'name_ar', label: 'المنتج' },
      { key: 'category_name', label: 'القسم' },
      { key: 'price', label: 'السعر (دينار)', money: true },
      { key: 'old_price', label: 'قبل الخصم', money: true },
      { key: 'stock', label: 'المخزون' },
      { key: 'is_featured', label: 'مميز' },
      { key: 'is_active', label: 'الحالة' },
    ],
    fields: [
      { key: 'name_ar', label: 'اسم المنتج', required: true },
      { key: 'name_en', label: 'الاسم بالإنجليزية' },
      { key: 'category_id', label: 'القسم', type: 'select', fromCategories: true },
      { key: 'price', label: 'السعر (دينار)', type: 'number', required: true },
      { key: 'old_price', label: 'السعر قبل الخصم (دينار)', type: 'number', hint: 'اتركه فارغاً إذا لم يكن هناك خصم' },
      { key: 'stock', label: 'المخزون', type: 'number' },
      { key: 'images_json', label: 'روابط الصور', type: 'images', hint: 'افصل بين الروابط بفاصلة' },
      { key: 'description', label: 'الوصف', type: 'textarea' },
      { key: 'is_featured', label: 'منتج مميز (يظهر في العروض)', type: 'checkbox' },
      { key: 'is_active', label: 'متوفر للبيع', type: 'checkbox' },
    ],
  },

  restaurants: {
    api: '/provider/menu-items',
    itemType: 'menu_items',
    categoriesApi: '/provider/menu-categories',
    title: 'قائمة الطعام',
    item: 'صنف',
    itemF: 'الصنف',
    icon: '🍽️',
    subtitle: 'أدر قائمة مطعمك وأقسامها وأسعار الأصناف',
    columns: [
      { key: 'name_ar', label: 'الصنف' },
      { key: 'category_name', label: 'القسم' },
      { key: 'price', label: 'السعر (دينار)', money: true },
      { key: 'is_available', label: 'متوفر الآن' },
      { key: 'is_featured', label: 'مميز' },
      { key: 'is_active', label: 'الحالة' },
    ],
    fields: [
      { key: 'name_ar', label: 'اسم الصنف', required: true },
      { key: 'name_en', label: 'الاسم بالإنجليزية' },
      { key: 'category_id', label: 'قسم القائمة', type: 'select', fromCategories: true },
      { key: 'price', label: 'السعر (دينار)', type: 'number', required: true },
      { key: 'images_json', label: 'روابط الصور', type: 'images', hint: 'افصل بين الروابط بفاصلة' },
      { key: 'description', label: 'الوصف', type: 'textarea' },
      { key: 'is_available', label: 'متوفر الآن', type: 'checkbox' },
      { key: 'is_featured', label: 'صنف مميز', type: 'checkbox' },
      { key: 'is_active', label: 'مفعل', type: 'checkbox' },
    ],
  },

  hotels: {
    api: '/provider/rooms',
    itemType: 'hotel_rooms',
    title: 'الغرف',
    item: 'غرفة',
    itemF: 'الغرفة',
    icon: '🏨',
    subtitle: 'أدر غرف فندقك وأسعارها وأنواعها وسعتها',
    columns: [
      { key: 'name_ar', label: 'الغرفة' },
      { key: 'room_type', label: 'النوع', roomType: true },
      { key: 'price_per_night', label: 'سعر الليلة (دينار)', money: true },
      { key: 'max_guests', label: 'النزلاء' },
      { key: 'is_featured', label: 'مميز' },
      { key: 'is_active', label: 'الحالة' },
    ],
    fields: [
      { key: 'name_ar', label: 'اسم الغرفة', required: true },
      { key: 'name_en', label: 'الاسم بالإنجليزية' },
      { key: 'room_type', label: 'نوع الغرفة', type: 'select', options: ROOM_TYPES },
      { key: 'price_per_night', label: 'السعر لليلة (دينار)', type: 'number', required: true },
      { key: 'max_guests', label: 'الحد الأقصى للنزلاء', type: 'number' },
      { key: 'images_json', label: 'روابط الصور', type: 'images', hint: 'افصل بين الروابط بفاصلة' },
      { key: 'description', label: 'الوصف', type: 'textarea' },
      { key: 'is_featured', label: 'غرفة مميزة (تظهر في العروض)', type: 'checkbox' },
      { key: 'is_active', label: 'مفعل', type: 'checkbox' },
    ],
  },

  flights: {
    api: '/provider/flights',
    itemType: 'flights',
    title: 'الرحلات',
    item: 'رحلة',
    itemF: 'الرحلة',
    icon: '✈️',
    subtitle: 'أدر رحلات الطيران ومواعيدها وأسعار تذاكرها',
    columns: [
      { key: 'flight_number', label: 'رقم الرحلة' },
      { key: 'airline', label: 'شركة الطيران' },
      { key: 'route', label: 'المسار', route: true },
      { key: 'departure_at', label: 'الإقلاع', datetime: true },
      { key: 'price', label: 'السعر (دينار)', money: true },
      { key: 'seats', label: 'المقاعد' },
      { key: 'is_featured', label: 'مميز' },
      { key: 'is_active', label: 'الحالة' },
    ],
    fields: [
      { key: 'flight_number', label: 'رقم الرحلة' },
      { key: 'airline', label: 'شركة الطيران' },
      { key: 'origin', label: 'رمز مطار المغادرة', hint: 'مثال: BGW' },
      { key: 'origin_ar', label: 'مدينة المغادرة' },
      { key: 'destination', label: 'رمز مطار الوصول', hint: 'مثال: NJF' },
      { key: 'destination_ar', label: 'مدينة الوصول' },
      { key: 'departure_at', label: 'موعد الإقلاع', type: 'datetime', required: true },
      { key: 'arrival_at', label: 'موعد الوصول', type: 'datetime' },
      { key: 'price', label: 'سعر التذكرة (دينار)', type: 'number', required: true },
      { key: 'seats', label: 'المقاعد المتاحة', type: 'number' },
      { key: 'is_featured', label: 'رحلة مميزة (تظهر في العروض)', type: 'checkbox' },
      { key: 'is_active', label: 'مفعل', type: 'checkbox' },
    ],
  },

  travel_offices: {
    api: '/provider/packages',
    itemType: 'travel_packages',
    title: 'الباقات',
    item: 'باقة',
    itemF: 'الباقة',
    icon: '🧳',
    subtitle: 'أدر باقات السفر السياحية ومكوناتها وأسعارها',
    columns: [
      { key: 'name_ar', label: 'الباقة' },
      { key: 'destination', label: 'الوجهة' },
      { key: 'duration_days', label: 'الأيام' },
      { key: 'price', label: 'السعر (دينار)', money: true },
      { key: 'is_featured', label: 'مميز' },
      { key: 'is_active', label: 'الحالة' },
    ],
    fields: [
      { key: 'name_ar', label: 'اسم الباقة', required: true },
      { key: 'name_en', label: 'الاسم بالإنجليزية' },
      { key: 'destination', label: 'الوجهة' },
      { key: 'duration_days', label: 'عدد الأيام', type: 'number' },
      { key: 'price', label: 'السعر (دينار)', type: 'number', required: true },
      { key: 'includes_json', label: 'ماذا تشمل الباقة', type: 'lines', hint: 'سطر لكل بند (مثال: تذاكر طيران ذهاب وعودة)' },
      { key: 'images_json', label: 'روابط الصور', type: 'images', hint: 'افصل بين الروابط بفاصلة' },
      { key: 'description', label: 'الوصف', type: 'textarea' },
      { key: 'is_featured', label: 'باقة مميزة (تظهر في العروض)', type: 'checkbox' },
      { key: 'is_active', label: 'مفعل', type: 'checkbox' },
    ],
  },
};

export const CATEGORY_CONFIG = {
  stores: { api: '/provider/product-categories', title: 'أقسام المنتجات', item: 'قسم', icon: '🗂️' },
  restaurants: { api: '/provider/menu-categories', title: 'أقسام القائمة', item: 'قسم', icon: '🗂️' },
};

export const CATEGORY_FIELDS = [
  { key: 'name_ar', label: 'الاسم بالعربية', required: true },
  { key: 'name_en', label: 'الاسم بالإنجليزية' },
  { key: 'icon', label: 'أيقونة' },
  { key: 'sort_order', label: 'الترتيب', type: 'number' },
  { key: 'is_active', label: 'مفعل', type: 'checkbox' },
];
